const prompt = require('prompt-sync')
const ajoutercandidat=require('./function/programe_function/ajoutercandidat.js')
const ajouterplusieurcnd=require('./function/programe_function/ajouterplusieurcnd.js')
const affichercandidat=require('./function/programe_function/affichercandidat.js')
const ajouterVote=require('./function/programe_function/ajoutervote.js')
const modiferinfocandidat=require('./function/programe_function/modifierinfocandidat.js')